### ISSUE TITLE
Speed up of catalog with large number of datasets

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#223]
Find some means of improving the speed of the catalog when there are a large number of files. This is particularly a problem on network shares.

Perhaps the answer is to allow an option to cache the catalog so that only new files are added. There would need to be a means of flushing the cache and forcing a full reload.

**Comment by srkline-igor** [comment]
the speed is what it is.

cache idea would be difficult to implement without errors. Months of work to save a few seconds.
