### ISSUE TITLE
data summary sort

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#310]
Steve and Andrew (I assume)

It would be useful to have a button under Raw data in SANS reduction to allow us to sort the data file catalog by label in the same way we can sort the files under transmission by label

Thanks

Larry

**Comment by krzywon** [comment]
[srkline] supposedly David at ANSTO has done this (6/2011), so if it could be incorporated...

**Comment by srkline-igor** [comment]
added the sort panel to the SANS macros, similar to what is in the VSANS macros, but with slightly different sort options.

Intent, Purpose, Group_ID can be added back to the sort panel if SANS switches to Nexus files
