### ISSUE TITLE
mock-up of VCALC

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#370]
as a first step for working with VSANS, use ideas from me, John, and Charles Dewhurst to come up with a mock-up of what the "VCALC" interface could look like. Don't waste a lot of time on the details of the back end, but try and figure out how the user could best interact with the instrument to get things set up for an optimal experiment. It's all new and there are a lot of things to move.

**Comment by krzywon** [comment]
[srkline] added r935
basics of the VCALC panel, at least for "SANS-type" measurements. Many details to fill in, but the framework is there. Slit geometry calculations are also there.

**Comment by srkline-igor** [comment]
close for now - more details will be added to VCALC, but the second version appears to work well.

Waiting for more input about what features are important to add.
