### ISSUE TITLE
Other ways to combine files -user suggestions for igor sans data reduction macros

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#399]
suggestions for igor sans data reduction plugins:
-possibility to merge a variable number (read: not necessarily 3) of runs into a merged file
-in 'sort and combine' possibility to select multiple non-adjacent files.

**Comment by srkline-igor** [comment]
close this ticket --- combining 4 files is now possible with the SORT operation panel. Adding a 5th would be a rare case, and would require a re-design of the panel and operation. There's simply not enough real estate for 5 data sets.

selection of multiple, non-adjacent files in the combine panel (not the SORT panel) is not likely that folks would need this much, especially with better (more consistent) definition of file names through the NICE GUI. A change like this would involve changing the table to be a list box (for the selection control), and would require a lot of effort to recreate all of the "table" functionality.
Not worth the effort
