### ISSUE TITLE
NSORT for 4 (or 5) geometries

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#400]
The NSORT_PANEL for isotropically averaged SANS data only supports runs for 3 different geometries. It would be good to have the option for an additional geometry there.

**Comment by krzywon** [comment]
[srkline] now people (Markus) are asking for NSORT to be able to handle 5 (4 SANS + 1 USANS)

Not sure how easy it would be to extend this, or how often it would be used.

**Comment by srkline-igor** [comment]
shelve this for now - until more folks ask for this to be extended to 5 sets. Using 4 sets now works well.
