### ISSUE TITLE
Copy and Paste Results of Invariant Calculations

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#402]
It would be great to be able to copy the results of the Invariant calculations for use in other software or simply for putting in tables.  At present, it seems that they must be copied by hand.

**Comment by krzywon** [comment]
[srkline] put on the which list (essentially shelved) since it's part of the unsupported analysis package

**Comment by srkline-igor** [comment]
close this - as an issue and leave it on my analysis wish list
