### ISSUE TITLE
Generate Nexus folder structure

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#415]
For write of simulated data from Igor - I may want to read in a NICE file, then auto-generate the folder structure from a modified version of DataFolderTree.ipf - and fill in the missing fields as needed (there may not be too many.) Then this will be a permanent template for writing out data files from VCALC.

There may be an easier way?

**Comment by srkline-igor** [comment]
Generating the whole Nexus structure on my own is really a pain.

An easier solution is to duplicate and renumber a single "good" raw data file, and then write out the "new" bits of the configuration and simulated data to the file, which will have the correct file structure.
