### ISSUE TITLE
add my XOP model function testing routines

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#492]
Add these plot/stress/speed tests to my library of functions. the most useful file to work with is located:

/Users/srkline/XOP and Model Testing/Testing_Procedures/TestAllPlotMacros.ipf

**Comment by srkline-igor** [comment]
not useful nay longer - analysis is taken on by sasView, and the analysis xop may not be supported much longer (macOS issues)
