### ISSUE TITLE
Mapped network drives on Windows 10

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#504]
windows 10 does not allow mapped network drives -- so can I relax the mapping requirement, or do we need to come up with a different solution.

try to remove the restriction first. I can't find documentation in my notes or in WM notes that requires a mapped drive. Igor 5+ 6+ brought better cross-platform path handling, which may remove that need.

**Comment by krzywon** [comment]
[srkline] the function to change is PickPath() in SANS_Utils.ipf

and

A_PickPath() in PlotUtilsMacro.ipf

currently it's commented out, but it has not been tested...

**Comment by srkline-igor** [comment]
as of Igor 7 and Igor 8, this doesn't seem to be an issue any longer. Closing ticket as fixed
