### ISSUE TITLE
combining 5 data sets using NSORT

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#512]
(from Markus Bleuel)

When combining SANS + USANS it is often helpful to have 5 geomteries in the SORT function (even so there is a difference due to the slit smearing)

**Comment by srkline-igor** [comment]
closed - this is a duplicate ticket, shelve until there is more demonstrated need for 5 sets with NSORT. 4 seems to be sufficient for now.
