### ISSUE TITLE
Data updates during protocol execution

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#529]
While a protocol is being executed, the data window title updates, but the displayed data does not. This is different behavior than the SANS reduction, and is not something that the user will be expecting. If nothing changes, it looks like something is wrong.

**Comment by krzywon** [comment]
[srkline] The file name in the status boxes on the panel now update correctly.

Still need to look into the issue of the file not updating as the steps are carried out.

**Comment by srkline-igor** [comment]
close the ticket - not hearing any issues with the window not updating. Maybe nobody ever looks at anything but the final data.
