### ISSUE TITLE
larger default mask

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#567]
need a larger default mask, + 3 tubes on outer 3 edges of the L/R panels. Maybe as many as 5 pixels.. See V_GenerateDetaultMask in MaskUtils.

**Comment by krzywon** [comment]
[srkline] sometimes the mask area needed is not obvious from the data set, and it's hard to tell whether the mask is too conservative, or not conservative enough.

**Comment by srkline-igor** [comment]
close for now. default mask may not be aggressive enough, but in practice glassy carbon is measured as a sample to give a data set that shows the necessary mask range for the actual experiment conditions
