### ISSUE TITLE
automatic identification of Transmission files

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#570]
Can the transmission files be automatically identified? rather than manually identified, and then the Purpose field entered manually.

Ideally, this should be done at the time of data collection from the GUI from a configuration that is in the transmission configuration.

But I may need a quick, foolproof way to identify transmission files. But how? can't look for the beam stop out of position.

**Comment by krzywon** [comment]
[srkline] working on this, using the newly written file comparisons -- so I can try to identify proper files for the transmission popups. Display only the files that match the conditions of the open beam -- don't show any files that are in a transmission configuration but have the beam on different panels.

**Comment by srkline-igor** [comment]
VSANS transmission files are labeled as such (intent). Nothing more.
