### ISSUE TITLE
SANS mode resolution

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#574]
in SANS mode, are all of the correct bits of information being fed to the calculation of the resolution function?

such as:
SSD - from the number of guides present
aperture sizes (especially the sample aperture)
SDD (including the offset from sample to gate valve)
- are all of the units what I'm expecting?

**Comment by srkline-igor** [comment]
everything looks to be correct with the pinhole resolution case. The values passed in are all what I'm expecting, and the smearing calculation looks correct as well.
