### ISSUE TITLE
speedup of USANS/VSANS matrix calculation

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#580]
can this be multithreaded?

**Comment by krzywon** [comment]
[srkline] Is this only for the fitting of VSANS slit-smeared data sets? If so, than this is a non-issue since fine-tuning of analysis is not for me to do.

**Comment by srkline-igor** [comment]
The calculation of the slit-smearing matrix, even three segments, is just as fast as for USANS. There is no speed issue here to deal with.
