### ISSUE TITLE
Plot the data from the slices with the timing information

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#584]
For event data, now that the slices can be written to a file with the timing information, think about how a user may want to see the data plotted.

Integrated counts vs. time
fitted (derived) value vs. time

Can I add the timing information to the reduced data file(s)?

**Comment by srkline-igor** [comment]
bins and timing are saved with the processed event data and can easily be re-plotted and tabulated by the user. shelve this until more feedback or a presented need to do something else. event data processing is very individual for each experiment, so I do not know what would be useful.
