### ISSUE TITLE
VCALC - automatic overlap

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#595]
Have a feature - on/off with a checkbox that will automatically move the 2nd carriage in response to the 1st to keep some degree of overlap with the q-range of the 1st carriage. Not sure how this will work with distance + panel separation + guides, but some automation may be helpful since there are so many things to move.

**Comment by srkline-igor** [comment]
close for now - doesn't seem to be terribly useful. Let the users and instrument scientists figure out how they need to understand the instrument configuration.
