### ISSUE TITLE
Event Mode - table to match scattering with event mode files

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#609]
generate a table to match the scattering files and the (2) event mode files.

Add the event mode file name fields to the patch panel (Reduction block? Instrument block?)

The event file loader looks for the event file name in the scattering file, so it needs to be present.

**Comment by srkline-igor** [comment]
added functionality to patch panel, and a separate function to generate a table accessible on the 2D tab
will be part of the 8.05 release
