### ISSUE TITLE
MASK files not showing up in the protocol popup

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#613]
currently, the MASK files are selected by simply searching for the *mask* in the file name. nothing more complex.

If the user gives a different name it will be missed.

I can try to force .MASK.h5 onto the end of the file name as a first fix.

**Comment by srkline-igor** [comment]
forcing .MASK.h5 extension on the saved mask seems to have solved the issue. (version prior to 8.01)
