### ISSUE TITLE
MASK file name parsing bug

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#615]
if there is a "dash" in the file name of a MASK or a DIV file, the protocol will report that the "BGD and EMP don't have the same configuration".

What is really happening is that the dash is telling Igor to parse out a range of run numbers - which is totally incorrect, and after it fails, sends out a bogus error message.

Solution - either make sure that there are never any dashes in the file names, or parse these file names differently. Don't try to parse dashes - there are never any runs to add together.

See the function V_MakeProtocolFromPanel()

**Comment by srkline-igor** [comment]
This was corrected in a version 8.01 or earlier. Not sure when, but the code was changed to ensure that the mask reading is a different routine that reads only that listed file, not trying to parse and look for multiple run numbers.
