### ISSUE TITLE
Rename files for QxQyASCII output

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#616]
currently the files are named:

fileNNNNN.DAT_ML (and similar) -- but the .DAT file extension needs to be preserved.

rename files of the form:

fileNNNNN_ML.DAT and similar.

be on the lookout for the Nexus definition which will put all of the reduced 2D data into a single file where it belongs

**Comment by srkline-igor** [comment]
this has been done (verified in v8.03), including COMBINED data files
