### ISSUE TITLE
units mismatch in resolution calculation

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#622]
It seems like line 136 (and line 284) in version 7.94 of NCNR_User_Procedures/Reduction/SANS/NCNR_utils.ipf have a unit mismatch - (applies to resolution calculation when lenses present)

{{{
v_b = 0.25*(S1*L2/L1)^2 +0.25*(2/3)*(lambdaWidth/lambda)^2*(S2*L2/lp)^2		//correction to 2nd term
}}}

because S1, L2 and L1 are in cm, the first term has units of cm^2^, which I would expect, but the second term has units of cm^2^/Angstroms, because lambdaWidth is unitless (it is delta_lambda/lambda) but lambda is in Angstroms, and S2, L2 and lp are in cm.

**Comment by srkline-igor** [comment]
corrected in both SANS and VSANS code. Was less than 5% correction to resolution value (sigmaQ)
Will be updated in version 8.05 release
