### ISSUE TITLE
projected pixel size goes to zero in -x, +y and -y, +x quadrants in resolution calculation

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#623]
in get2DResolution function, line 324 of NCNR_User_Procedures/Reduction/SANS/NCNR_utils.ipf (version 7.94) the projected detector size is calculated as
{{{
	// the detector pixel is square, so correct for phi
	proj_DDet = DDet*cos(phi) + DDet*sin(phi)
}}}

but this will have the desired behavior (proj_DDet=DDet along x and y, but bigger in between the axes) only where x,y are both positive or both negative.  Where the sign of x and y differ, the sign of cos and sin in the expression will differ and you will get a subtraction where you I think always want an addition.

In particular, when x = -y you will get complete cancellation, and proj_DDet will be zero! (at an angle of 3*pi/4 and 7*pi/4)

**Comment by srkline-igor** [comment]
corrected in both SANS and VSANS code, will be in the version 8.05 release
