### ISSUE TITLE
column read error in USANS (BT5 loader for NCNR)

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#628]
There seems to be an index error in the BT5_loader.ipf routine - it on line 155 (or 154 with zero-indexing) it says:
{{{
v4 = v6/(1.0-v4*MainDeadTime/countTime)   // Deadtime correction
}}}

when probably it should say:
{{{
v4 = v4/(1.0-v4*MainDeadTime/countTime)   // Deadtime correction
}}}

**Comment by srkline-igor** [comment]
This bug was fixed in the v7.99 release
