### ISSUE TITLE
Allow loading of files from contextual menu in file catalog

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#629]
Since the method used in VSANS has been well received, do the same in SANS - to allow loading of data files (RAW, MSK, DIV + ?) from a contextual menu in the file catalog window.

The hook function could easily be ported over and modified to SANS-specific content.

Think about anything else that would be useful to add for SANS reduction.

**Comment by srkline-igor** [comment]
This was added in v7.99
