### ISSUE TITLE
Automatic install of HDF5 XOP

### ISSUE THREAD

**Issue by srkline-igor** [sansigormacros/ncnrsansigormacros#659]
I am seeing too many emails where the xop is not installed - it needs to be part of the installer. Don't know how I can do this automatically.

If I try to install a static copy of the xop, then there will be issues if someone already has the xop installed as a shortcut. Bad.

But otherwise - errors and big hassles for anyone trying to start out with the software.

**Comment by krzywon** [comment]
I was about to make this same ticket... I'm going update the release notes with instructions on how to enable the XOP.

**Comment by srkline-igor** [comment]
If there are two shortcuts for the HDF5 xop - the XOP is loaded twice. There are duplicate copies of all of the HDF5 functions and operations when I look at the command browser. 

Ask Jan if he has a way to safely do this type of install, put the question to the mailing list, and finally to Howard at Wavemetrics.

Much of this will go away with Igor 9, as the HDF5 operations are all built-in and the XOP is not needed in Igor 9.

**Comment by srkline-igor** [comment]
Jeff got this to work, and it's now part of the installer package for the 8.02 release version
