### ISSUE TITLE
Help files on NCNR Webpage

### ISSUE THREAD

**Issue by srkline-igor** [sansigormacros/ncnrsansigormacros#663]
Can I add the help files - the current version - to the repository as pdf files so that they can be linked to the NCNR web page, and be the current versions.

Do I then need to exclude the pdf files from the package? - to keep the size of the package smaller - since it's already getting rather large.

**Comment by krzywon** [comment]
We could store the PDFs, and potentially other files, in a separate repository, e.g. sansigormacros/docs, so they remain separate from the main package.

**Comment by srkline-igor** [comment]
Hi Jeff,

Setting up a separate repository for /docs sounds like a good idea. It'll keep those pdfs to link to the web page in a separate place, since they aren't "code" and not necessary as part of the package. I can keep the same names for linked files and updates will be instantly accessible. Good idea.

A couple of things that I haven't got figured out - but maybe you have ideas.

I'd love to have a better place where other documentation could be placed - where it is publicly accessible - things like the video documentation. NISTube is fine, but it's only for NIST folks, so it's not terribly helpful. NISTube has the associated WERB issues as well if my videos go "public". Putting them on some /Docs area on github - I don't know how excited github would be to store a lot of videos. I don't know how much bandwidth viewing would eat up on github, or if they would allow video documentation.

I also have more "internal" documentation that I'd like to make visible to SANS staff, mostly. I've got a lot of documentation (similar to John's memos), docs that explain/verify the program operation and other details of the code - not necessarily information to toss out to the whole wide world. Something internal, or with access control here would be helpful - but I'm not sure if github will allow this, either. I didn't see any description of this kind of control/privacy in github docs.

If you've got any ideas for these situations, let me know.

Steve


__________________________________________
Dr. Steven Kline
NIST Center for Neutron Research
100 Bureau Drive, Stop 6102
Gaithersburg, MD 20899-6102
ph (301) 975-6243, fax (301) 921-9847

________________________________

**Comment by srkline-igor** [comment]
The  /docs repository has been created to house the pdf versions of the help files, and these pdf files are now linked to the web page. I will manually update/commit pdf versions of any changed help files - when they are updated (if significant) or at least when a new package is released.
