### ISSUE TITLE
Missing bin in Annular average for VSANS

### ISSUE THREAD

**Issue by Y-FLee** [sansigormacros/ncnrsansigormacros#673]
I would like to report a issue associated with the VSANS annular average. It is found that the last bin of the annular average is missing. For example, if 6-degree-bin is applied, one should have 0, 6, 12, ....., all the way to 354 degrees. However, I only got the "348 degree" as the last annular bin (see the attached file), which means the real last bin "354 degree" is missing in some way.

[sans44891.txt](https://github.com/sansigormacros/ncnrsansigormacros/files/6965000/sans44891.txt)

**Comment by krzywon** [comment]
Thanks for the report, @Y-FLee. This seems similar to an issue that was recently fixed, #672. The fix will be available in the next release. Could you take a look and comment if this is different, or close this issue if they are the same?

**Comment by Y-FLee** [comment]
You are right. The issue is the same. Thanks for fixing it.
